name:  ld28
description: LD28 - You Only Get One
dependencies:
  a_star: any
  browser: any
  gamedev_helpers:
#    git: https://github.com/denniskaselow/gamedev_helpers
    path: ../gamedev_helpers
  dart_to_js_script_rewriter: any
transformers:
- dart_to_js_script_rewriter